### ISSUE TITLE
Can the wireless network card be directly connected to Android through device/dev/bus/usb/002/002?

### ISSUE THREAD

**Issue by nongze** [CNflysky/redroid-rk3588#15]
**NOTICE: ANY BUG REPORT NOT USING THIS TEMPLETE WILL BE CLOSED AS NOT PLANNED**
**注意：任何未使用该模板的错误报告将被直接关闭**

**Describe the bug**
**描述Bug**
Can I directly connect the wireless network card to Android through `--device /dev/bus/usb/002/002` and use its wireless and Bluetooth functions?
能不能通过--device /dev/bus/usb/002/002将无线网卡直通进入安卓，并使用它的无线、蓝牙功能？
**Required Information**
**基本信息**
- docker image name
- 镜像名称
`12.0.0-latest`

- Board Information
- 板卡信息
 `Orange Pi 5 + 8 GB RAM`

- OS Information
- 系统信息
 `Debian Bookworm Server`

- Kernel version
- 内核版本
`5.10.160-rockchip-rk3588`

**To Reproduce**
**复现步骤**
My startup command.
我的启动命令
`docker run -d -p 5551:5555 -v ~/redroid-data:/data --privileged -v /dev/bus/usb:/dev/bus/usb --device /dev/bus/usb/002/002 --restart unless-stopped --name redroid 4185bcc3baa1  androidboot.redroid_height=1920 androidboot.redroid_width=1080 androidboot.redroid_magisk=1 androidboot.redroid_fake_wifi=1
`
**Screenshots**
**截图**
![C{DL_ 4G6LW5B5YU`1BN} B_tmb](https://github.com/user-attachments/assets/9a35a40e-832c-4c6c-b7da-2513d7bf8f75)

**Additional context**
**附加说明**
 none
无

**Comment by CNflysky** [comment]
no. WLAN interface (wlan0,wlan1,.etc) can only be created with kernel drivers, redroid don't know how to communicate with USB WiFi adapters through its USB file descriptor.

不行。wlan接口（wlan0,wlan1等等）只能通过内核驱动来创建，redroid并不知道如何与USB WiFi的文件描述符来通信。
