### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rtedpro-cpu** [CNflysky/redroid-rk3588#19]
Is this only for arm or is too for x86_64?
I am also intrested how you did the fake wifi with the option of choosing fake wifi said?

**Comment by SeeleVolleri** [comment]
For RK3588(s) only, not for X86.

**Comment by CNflysky** [comment]
> Thats fine, just wanna know how did you do the fake wifi

take a look at [waydroid-patch](https://github.com/waydroid/android_vendor_waydroid/blob/lineage-18.1/waydroid-patches/base-patches-30/frameworks/base/0041-Fake-wifi-connection-for-select-apps.patch)
