### ISSUE TITLE
功能期望

### ISSUE THREAD

**Issue by XiaoMing-Fish** [CNflysky/redroid-rk3588#20]
**NOTICE: ANY BUG REPORT NOT USING THIS TEMPLETE WILL BE CLOSED AS NOT PLANNED**
**注意：任何未使用该模板的错误报告将被直接关闭**

**Describe the bug**
**描述Bug**
提供一个清晰简洁的问题描述
是否添加虚拟电池
是否能代理ip
能否集成改机
**Required Information**
**基本信息**
- docker image name
- 镜像名称
e.g. `13.0.0-latest`
12.0.0-latest
- Board Information
- 板卡信息
e.g. `Orange Pi 5 Plus + 16 GB RAM`
Orange Pi 5 Plus + 16 GB RAM
- OS Information
- 系统信息
e.g. `Armbian Bookworm Server`
Debian 11 (bullseye)
- Kernel version
- 内核版本
e.g. `5.10.160-rockchip-rk35xx`
5.10.160-rockchip-rk3588

**To Reproduce**
**复现步骤**
以下是复现该问题的步骤：

**Screenshots**
**截图**
如果可以，添加一些截图以更好地解释问题

**Additional context**
**附加说明**
logcat messages are suggested place into pastebin.
如果有额外的问题说明，请放在这里
logcat信息建议放在pastebin里

**Comment by CNflysky** [comment]
虚拟电池可以通过在/sys下放置一些文件来实现（`/sys/power`）
不太清楚你说的代理IP是什么，如果是VPN的话，已经支持了
修改设备信息可以通过挂载prop的方式实现

**Comment by XiaoMing-Fish** [comment]
vpn这个没看到设置的属性
ro修改prop视乎无效
电池这个我会试试看
tks

**Comment by XiaoMing-Fish** [comment]
设备再用第三方代理apk会闪退，例如奇游加速器

**Comment by CNflysky** [comment]
> 设备再用第三方代理apk会闪退，例如奇游加速器

请提供日志，须知「在没有日志的情况下就诊断问题无异于闭眼开车」

**Comment by CNflysky** [comment]
> vpn这个没看到设置的属性
> ro修改prop视乎无效
> 电池这个我会试试看
> tks

#5

**Comment by SeeleVolleri** [comment]
modprobe tun

**Comment by SeeleVolleri** [comment]
modprobe tun

发自我的iPhone

**Comment by CNflysky** [comment]
善用issue搜索功能
