### ISSUE TITLE
有没有人和我一样，容器起来，但是看不到安卓界面

### ISSUE THREAD

**Issue by myallten** [CNflysky/redroid-rk3588#21]
**NOTICE: ANY BUG REPORT NOT USING THIS TEMPLETE WILL BE CLOSED AS NOT PLANNED**
**注意：任何未使用该模板的错误报告将被直接关闭**

**Describe the bug**
**描述Bug**
容器能跑起来，但是通过QtScrcpy连接就是无法显示安卓界面

**Required Information**
**基本信息**
- docker image name
root@ubuntu:/userdata# docker images
REPOSITORY                TAG             IMAGE ID       CREATED        SIZE
cnflysky/redroid-rk3588   12.0.0-latest   eea094493867   2 months ago   2.12GB

e.g. `12.0.0-latest`

- Board Information
- 板卡信息
- RK3588S开发板
e.g. `root@ubuntu:/userdata# uname -a
Linux ubuntu 5.10.160 #611 SMP Wed Oct 9 14:37:59 CST 2024 aarch64 aarch64 aarch64 GNU/Linux
 16G 内存 128G存储`

- OS Information
- 系统信息
e.g. `root@ubuntu:/userdata# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
OS="ubuntu"
BUILD_INFO="root@hgs123 Wed Oct  9 17:21:59 CST 2024"
KERNEL="5.10 - rockchip_linux_defconfig"`

- Kernel version
- 内核版本
e.g. `5.10.160-rockchip-rk35xx`

**To Reproduce**
**复现步骤**
以下是复现该问题的步骤：
使用的docker -compose.yaml
version: '3'
services:
  redroid:
    image: cnflysky/redroid-rk3588:12.0.0-latest
    container_name: redroid
    restart: unless-stopped
    privileged: true
    ports:
      - "5556:5555"
    volumes:
      - "~/redroid-data:/data"
    command:
      - "androidboot.redroid_width=1080"
      - "androidboot.redroid_height=1920"

      # uncomment following line to enable magisk
      # - "androidboot.redroid_magisk=1"

      # uncomment following line to enable fake wifi
      # - "androidboot.redroid_fake_wifi=1"

      # see https://source.android.com/docs/setup/create/new-device PRODUCT_CHARACTERISTICS 
      - "ro.build.characteristics=default"
      # uncomment following line to enable adb authentication
      # - "ro.adb.secure=1"

**Screenshots**
**截图**
如果可以，添加一些截图以更好地解释问题

root@ubuntu:/userdata# docker ps
CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS          PORTS                                         NAMES
cf1f4b1a3828   cnflysky/redroid-rk3588:12.0.0-latest   "/init androidboot.h…"   20 minutes ago   Up 20 minutes   0.0.0.0:5556->5555/tcp, [::]:5556->5555/tcp   redroid

![20241012171851](https://github.com/user-attachments/assets/bee547f8-fdee-4c80-aaac-793b96966576)
![20241012171811](https://github.com/user-attachments/assets/4f44a095-5c82-492e-a8f2-9bf186897028)

**Additional context**
**附加说明**
logcat messages are suggested place into pastebin.
如果有额外的问题说明，请放在这里
logcat信息建议放在pastebin里

**Comment by SeeleVolleri** [comment]
参阅文档中系统要求部分
