### ISSUE TITLE
加群目前有问题，需要怎么样才可以加qq群

### ISSUE THREAD

**Issue by chenyi751** [CNflysky/redroid-rk3588#23]

**Comment by chenyi751** [comment]
加群要输入  soc型号是？  这个只能回答固定的答案，这个要填写什么信息

**Comment by chenzhu005774** [comment]
> 加群要输入 soc型号是？ 这个只能回答固定的答案，这个要填写什么信息

RK3588 or rk3588 or Rk3588

**Comment by 863401402** [comment]
新密码是多少呢 rk3588已经失效了

**Comment by chenzhu005774** [comment]
不太清楚 我不是群主



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月9日(星期一) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CNflysky/redroid-rk3588] 加群目前有问题，需要怎么样才可以加qq群 (Issue #23)














 
新密码是多少呢 rk3588已经失效了
