### ISSUE TITLE
机型伪装

### ISSUE THREAD

**Issue by 577214302** [CNflysky/redroid-rk3588#26]
**NOTICE: ANY BUG REPORT NOT USING THIS TEMPLETE WILL BE CLOSED AS NOT PLANNED**
**注意：任何未使用该模板的错误报告将被直接关闭**

**Describe the bug**
**描述Bug**
修改不了机型 通过面具安装的应用伪装 应用变量 等修改机型的软件都无效 能非在启动的时候提供机型伪装 例如 docker run -itd --rm --memory-swappiness=0 \
    --privileged --pull always \
    -v /data:/data \
    -p 5555:5555 \
    redroid/redroid:11.0.0-latest \
    androidboot.hardware=mt6891 ro.secure=0 ro.boot.hwc=GLOBAL ro.ril.oem.imei=861503068361145 ro.ril.oem.imei1=861503068361145 ro.ril.oem.imei2=861503068361148 ro.ril.miui.imei0=861503068361148 ro.product.manufacturer=Xiaomi ro.build.product=chopin \
    redroid.width=720 redroid.height=1280 \
    redroid.gpu.mode=guest

**Required Information**
**基本信息**
- docker image name
- 镜像名称
e.g. `12.0.0-latest`

- Board Information
- 板卡信息
e.g. `Orange Pi 5  + 18GB RAM`

- OS Information
- 系统信息
e.g. `Armbian Bookworm Server`

- Kernel version
- 内核版本
e.g. `5.10.160-rockchip-rk35xx`

**To Reproduce**
**复现步骤**
以下是复现该问题的步骤：

**Screenshots**
**截图**
如果可以，添加一些截图以更好地解释问题

**Additional context**
**附加说明**
logcat messages are suggested place into pastebin.
如果有额外的问题说明，请放在这里
logcat信息建议放在pastebin里

**Comment by CNflysky** [comment]
`redroid-rk3588` will not add support for physical device emulation.
