### ISSUE TITLE
日服碧蓝报错

### ISSUE THREAD

**Issue by zhenghan123** [CNflysky/redroid-rk3588#27]
问题

https://github.com/user-attachments/assets/7179f1b3-d6b9-4507-b8f1-f21a21a592ec

镜像
cnflysky/redroid-rk3588:lineage-20

- 板卡信息
Orange Pi 5 Plus + 8 GB RAM

- OS Information
- 系统信息
Ubuntu 22.04 LTS

- 内核版本
5.10.0-1012-rockchip

**复现步骤**
以下是复现该问题的步骤：
直接点击游戏

**Comment by CNflysky** [comment]
#3

**Comment by CNflysky** [comment]
paste some log plz
```bash
docker stop redroid -t 0
docker start redroid
docker exec redroid logcat | tee -a logcat.log
#open game, wait it crash, then upload the log file (logcat.log)
```

**Comment by CNflysky** [comment]
okay on my device
![Screenshot_20241223-172832_Trebuchet.png](https://github.com/user-attachments/assets/8223c7fc-89bd-4852-9360-340c6bafba7b)

**Comment by CNflysky** [comment]
where did you get the game？`Google Play`？sometimes 3rd-party apk store could missing game required components like library or obb.

**Comment by CNflysky** [comment]
download it from `apkpure` please
https://apkpure.com/cn/%E3%82%A2%E3%82%BA%E3%83%BC%E3%83%AB%E3%83%AC%E3%83%BC%E3%83%B3/com.YoStarJP.AzurLane

**Comment by CNflysky** [comment]
run `envcheck.sh` and paste the result.

**Comment by CNflysky** [comment]
i guess previous kernel update was not successful so your board still running stock kernel. anyway, problem solved.
